#!/bin/bash
cd "$(dirname "${BASH_SOURCE[1]}")"
echo "Se van a compilar todas las versiones de realign.c."
rm -rf v0
rm -rf v1
rm -rf v2
rm -rf v3a
rm -rf v3b
rm -rf vex
cp code/* .
./build v0
./build v1
./build v2
./build v3a
./build v3b
./build vex

ssh -Y -l $1@alumno.upv.es kahan.dsic.upv.es